/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedShippingRouteImport } from './routes/_authenticated/shipping'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses.index'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedOrdersNewRouteImport } from './routes/_authenticated/orders.new'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedExpensesNewRouteImport } from './routes/_authenticated/expenses.new'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedProductsIdEditRouteImport } from './routes/_authenticated/products.$id.edit'
import { Route as AuthenticatedOrdersIdEditRouteImport } from './routes/_authenticated/orders.$id.edit'
import { Route as AuthenticatedExpensesIdEditRouteImport } from './routes/_authenticated/expenses.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShippingRoute = AuthenticatedShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersNewRoute = AuthenticatedOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesNewRoute =
  AuthenticatedExpensesNewRouteImport.update({
    id: '/expenses/new',
    path: '/expenses/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedProductsIdEditRoute =
  AuthenticatedProductsIdEditRouteImport.update({
    id: '/products/$id/edit',
    path: '/products/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdEditRoute =
  AuthenticatedOrdersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedOrdersIdRoute,
  } as any)
const AuthenticatedExpensesIdEditRoute =
  AuthenticatedExpensesIdEditRouteImport.update({
    id: '/expenses/$id/edit',
    path: '/expenses/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/labels': typeof AuthenticatedLabelsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shipping': typeof AuthenticatedShippingRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/expenses/$id/edit': typeof AuthenticatedExpensesIdEditRoute
  '/orders/$id/edit': typeof AuthenticatedOrdersIdEditRoute
  '/products/$id/edit': typeof AuthenticatedProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/labels': typeof AuthenticatedLabelsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shipping': typeof AuthenticatedShippingRoute
  '/': typeof AuthenticatedIndexRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/expenses/$id/edit': typeof AuthenticatedExpensesIdEditRoute
  '/orders/$id/edit': typeof AuthenticatedOrdersIdEditRoute
  '/products/$id/edit': typeof AuthenticatedProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shipping': typeof AuthenticatedShippingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/_authenticated/orders/new': typeof AuthenticatedOrdersNewRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/expenses/$id/edit': typeof AuthenticatedExpensesIdEditRoute
  '/_authenticated/orders/$id/edit': typeof AuthenticatedOrdersIdEditRoute
  '/_authenticated/products/$id/edit': typeof AuthenticatedProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/customers'
    | '/labels'
    | '/reports'
    | '/settings'
    | '/shipping'
    | '/customers/$id'
    | '/expenses/new'
    | '/orders/$id'
    | '/orders/new'
    | '/products/new'
    | '/expenses/'
    | '/orders/'
    | '/products/'
    | '/expenses/$id/edit'
    | '/orders/$id/edit'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/customers'
    | '/labels'
    | '/reports'
    | '/settings'
    | '/shipping'
    | '/'
    | '/customers/$id'
    | '/expenses/new'
    | '/orders/$id'
    | '/orders/new'
    | '/products/new'
    | '/expenses'
    | '/orders'
    | '/products'
    | '/expenses/$id/edit'
    | '/orders/$id/edit'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/customers'
    | '/_authenticated/labels'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/shipping'
    | '/_authenticated/'
    | '/_authenticated/customers/$id'
    | '/_authenticated/expenses/new'
    | '/_authenticated/orders/$id'
    | '/_authenticated/orders/new'
    | '/_authenticated/products/new'
    | '/_authenticated/expenses/'
    | '/_authenticated/orders/'
    | '/_authenticated/products/'
    | '/_authenticated/expenses/$id/edit'
    | '/_authenticated/orders/$id/edit'
    | '/_authenticated/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipping': {
      id: '/_authenticated/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof AuthenticatedShippingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/new': {
      id: '/_authenticated/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthenticatedOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/new': {
      id: '/_authenticated/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AuthenticatedExpensesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/products/$id/edit': {
      id: '/_authenticated/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AuthenticatedProductsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$id/edit': {
      id: '/_authenticated/orders/$id/edit'
      path: '/edit'
      fullPath: '/orders/$id/edit'
      preLoaderRoute: typeof AuthenticatedOrdersIdEditRouteImport
      parentRoute: typeof AuthenticatedOrdersIdRoute
    }
    '/_authenticated/expenses/$id/edit': {
      id: '/_authenticated/expenses/$id/edit'
      path: '/expenses/$id/edit'
      fullPath: '/expenses/$id/edit'
      preLoaderRoute: typeof AuthenticatedExpensesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedOrdersIdRouteChildren {
  AuthenticatedOrdersIdEditRoute: typeof AuthenticatedOrdersIdEditRoute
}

const AuthenticatedOrdersIdRouteChildren: AuthenticatedOrdersIdRouteChildren = {
  AuthenticatedOrdersIdEditRoute: AuthenticatedOrdersIdEditRoute,
}

const AuthenticatedOrdersIdRouteWithChildren =
  AuthenticatedOrdersIdRoute._addFileChildren(
    AuthenticatedOrdersIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShippingRoute: typeof AuthenticatedShippingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedExpensesNewRoute: typeof AuthenticatedExpensesNewRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRouteWithChildren
  AuthenticatedOrdersNewRoute: typeof AuthenticatedOrdersNewRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedExpensesIdEditRoute: typeof AuthenticatedExpensesIdEditRoute
  AuthenticatedProductsIdEditRoute: typeof AuthenticatedProductsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShippingRoute: AuthenticatedShippingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedExpensesNewRoute: AuthenticatedExpensesNewRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRouteWithChildren,
  AuthenticatedOrdersNewRoute: AuthenticatedOrdersNewRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedExpensesIdEditRoute: AuthenticatedExpensesIdEditRoute,
  AuthenticatedProductsIdEditRoute: AuthenticatedProductsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
